drop table if exists member CASCADE;
create table member
(
	 id bigint generated by default as identity,
	 name varchar(255),
	 primary key (id)
);drop table if exists member CASCADE;
create table member
(
	 id bigint generated by default as identity,
	 name varchar(255),
	 primary key (id)
);
/*
sql 파일 또한 깃에 등록하여 관리하면 좋다.
 */